import { choice, integer, object, text, time, uuid } from "../schemas.ts";
export const examNumber = {
  type: "string",
  pattern: "^-?(0|[1-9][0-9]{0,15})(\\.[0-9]{1,8})?$",
};
export const examBoolean = { type: "boolean" };
const age = { type: "integer", minimum: 0, maximum: 2147483647 };
const note = { ...text, maxLength: 2000 };
const common = {
  unidade_id: uuid,
  motivo: text,
  simulacao: { type: "boolean", const: true },
  confirmacao_humana: { type: "boolean", const: true },
};
const attribute = {
  codigo: text,
  descricao: text,
  tipo: choice("numero", "texto", "booleano"),
  unidade: text,
  obrigatorio: examBoolean,
  ordem: integer,
};
const value = {
  atributo_id: uuid,
  situacao: choice("informado", "nao_obtido"),
  texto_original: note,
  numero: examNumber,
  booleano: examBoolean,
  qualificador: choice(
    "igual",
    "menor",
    "menor_igual",
    "maior",
    "maior_igual",
    "nao_aplicavel",
  ),
  referencia_id: uuid,
  referencia_status: choice("informada", "pendente", "nao_aplicavel"),
  observacao: note,
};
export const examInputs = {
  examLab: object({
    ...common,
    nome: text,
    origem: choice("interno", "externo"),
    identificacao: text,
  }),
  examCatalog: object({ ...common, item_clinico_id: uuid, codigo: text }),
  examVersion: object({
    ...common,
    exame_id: uuid,
    versao: integer,
    descricao: text,
    laboratorio_id: uuid,
    metodo: text,
    exige_coleta: examBoolean,
    material: text,
    atributos: {
      type: "array",
      minItems: 1,
      maxItems: 100,
      items: object(attribute),
    },
  }),
  examApprove: object({ ...common, exame_versao_id: uuid }),
  examReference: object(
    {
      ...common,
      atributo_id: uuid,
      versao: integer,
      codigo: text,
      especie_codigo: choice("canina", "felina", "outra", "desconhecida"),
      idade_min_dias: age,
      idade_max_dias: age,
      inclui_idade_min: examBoolean,
      inclui_idade_max: examBoolean,
      limite_inferior: examNumber,
      limite_superior: examNumber,
      inclui_inferior: examBoolean,
      inclui_superior: examBoolean,
      descricao: note,
    },
    [
      ...Object.keys(common),
      "atributo_id",
      "versao",
      "codigo",
      "especie_codigo",
      "inclui_idade_min",
      "inclui_idade_max",
      "inclui_inferior",
      "inclui_superior",
      "descricao",
    ],
  ),
  examRequest: object({
    ...common,
    episodio_id: uuid,
    solicitada_em: time,
    indicacao: note,
    referencia: uuid,
    itens: {
      type: "array",
      minItems: 1,
      maxItems: 20,
      items: object({ exame_versao_id: uuid }),
    },
  }),
  examCancel: object({ ...common, item_exame_id: uuid }),
  examSample: object(
    {
      ...common,
      item_exame_id: uuid,
      referencia: uuid,
      coletada_em: time,
      material: text,
      origem: choice("interna", "externa"),
      execucao_id: uuid,
      coletor_informado: text,
      evidencia: note,
    },
    [
      ...Object.keys(common),
      "item_exame_id",
      "referencia",
      "coletada_em",
      "material",
      "origem",
      "evidencia",
    ],
  ),
  examSampleDecision: object({
    ...common,
    coleta_id: uuid,
    situacao: choice("aceita", "rejeitada"),
    avaliada_em: time,
  }),
  examResult: object(
    {
      ...common,
      item_exame_id: uuid,
      versao_esperada: age,
      coleta_id: uuid,
      produzido_em: time,
      referencia: uuid,
      idade_dias: age,
      origem_idade: choice("desconhecida", "informada", "estimada"),
      observacao: note,
      valores: {
        type: "array",
        minItems: 1,
        maxItems: 100,
        items: object(value, [
          "atributo_id",
          "situacao",
          "texto_original",
          "qualificador",
          "referencia_status",
          "observacao",
        ]),
      },
    },
    [
      ...Object.keys(common),
      "item_exame_id",
      "versao_esperada",
      "produzido_em",
      "referencia",
      "origem_idade",
      "observacao",
      "valores",
    ],
  ),
  examRelease: object({
    ...common,
    resultado_id: uuid,
    pendencias_confirmadas: examBoolean,
  }),
};
export const examPermissions = [
  "exames:ler",
  "exames:configurar",
  "exames:aprovar_simulacao",
  "exames:solicitar",
  "exames:coletar",
  "exames:avaliar_amostra",
  "exames:registrar_resultado",
  "exames:liberar",
  "exames:cancelar",
];
