function project(
  table: string,
  alias: string,
  patient: string,
  episode: string,
  author: string,
  type: string,
  nature: string,
  state: string,
  occurred: string,
  registered: string,
  current: string,
  join = "",
) {
  return `SELECT ${alias}.id,${alias}.organizacao_id,${alias}.unidade_id,${patient} AS paciente_id,${episode} AS episodio_id,${author} AS autor_id,'${type}'::text AS tipo,'${nature}'::text AS natureza,${state} AS situacao,${occurred} AS ocorrido_em,${registered} AS registrado_em,${current} AS atual FROM ${table} ${alias} ${join}`;
}
const episodeJoin = (alias: string) =>
  `JOIN episodio ep ON ep.organizacao_id=${alias}.organizacao_id AND ep.id=${alias}.episodio_id`;
export const timelineSources: Record<
  string,
  { permissions: string[]; sql: string[] }
> = {
  evolucoes: {
    permissions: [],
    sql: [
      project(
        "evolucao_clinica_versao_consulta",
        "v",
        "v.paciente_id",
        "v.episodio_id",
        "v.autor_id",
        "evolucao",
        "relato",
        "CASE WHEN v.revisao_temporal THEN 'revisao_temporal' ELSE v.estado END",
        "v.ocorrida_em",
        "v.criada_em",
        "v.atual",
      ),
    ],
  },
  clinica: {
    permissions: ["clinica:ler", "episodios:ler"],
    sql: [
      project(
        "episodio",
        "v",
        "v.paciente_id",
        "v.id",
        "v.autor_id",
        "episodio",
        "registro",
        "CASE WHEN v.encerrado_em IS NOT NULL THEN 'encerrado' WHEN v.alta_clinica_em IS NOT NULL THEN 'alta_clinica' ELSE 'aberto' END",
        "v.admitido_em",
        "v.registrado_em",
        "true",
      ),
      project(
        "prescricao",
        "v",
        "ep.paciente_id",
        "v.episodio_id",
        "v.prescritor_id",
        "prescricao",
        "registro",
        "'registrada'::text",
        "v.assinada_em",
        "v.registrada_em",
        "true",
        episodeJoin("v"),
      ),
      project(
        "ordem_versao",
        "v",
        "ep.paciente_id",
        "v.episodio_id",
        "v.autor_id",
        "ordem",
        "planejamento",
        "'prescrita'::text",
        "v.vigencia_inicio",
        "v.registrada_em",
        "NOT EXISTS(SELECT 1 FROM ordem_versao n WHERE n.organizacao_id=v.organizacao_id AND n.ordem_id=v.ordem_id AND n.versao>v.versao)",
        episodeJoin("v"),
      ),
      project(
        "programacao_consulta",
        "v",
        "ep.paciente_id",
        "v.episodio_id",
        "v.autor_id",
        "programacao",
        "planejamento",
        "v.situacao",
        "v.prevista_em",
        "v.criada_em",
        "true",
        episodeJoin("v"),
      ),
      project(
        "execucao_consulta",
        "v",
        "ep.paciente_id",
        "v.episodio_id",
        "v.executor_id",
        "execucao",
        "execucao",
        "CASE WHEN v.anulacao_id IS NOT NULL THEN 'anulada' ELSE v.resultado END",
        "v.executada_em",
        "v.registrada_em",
        "v.substituida_por_id IS NULL AND v.anulacao_id IS NULL",
        episodeJoin("v"),
      ),
      project(
        "revisao_execucao",
        "v",
        "ep.paciente_id",
        "v.episodio_id",
        "v.autor_id",
        "correcao_execucao",
        "retificacao",
        "v.tipo",
        "v.criada_em",
        "v.criada_em",
        "true",
        episodeJoin("v"),
      ),
      project(
        "consumo_consulta",
        "v",
        "ep.paciente_id",
        "v.episodio_id",
        "v.autor_id",
        "consumo",
        "consumo",
        "v.situacao",
        "v.ocorrido_em",
        "v.registrado_em",
        "v.estorno_id IS NULL",
        episodeJoin("v"),
      ),
      project(
        "estorno_consumo",
        "v",
        "ep.paciente_id",
        "c.episodio_id",
        "v.autor_id",
        "estorno_consumo",
        "estorno",
        "'registrado'::text",
        "v.ocorrido_em",
        "v.registrado_em",
        "true",
        "JOIN consumo c ON c.organizacao_id=v.organizacao_id AND c.id=v.consumo_id JOIN episodio ep ON ep.organizacao_id=c.organizacao_id AND ep.id=c.episodio_id",
      ),
    ],
  },
  exames: {
    permissions: ["exames:ler"],
    sql: [
      project(
        "resultado_exame_consulta",
        "v",
        "ep.paciente_id",
        "v.episodio_id",
        "v.autor_id",
        "resultado_exame",
        "resultado",
        "CASE WHEN v.liberado THEN 'liberado_dev' ELSE 'nao_liberado' END",
        "v.produzido_em",
        "v.criada_em",
        "NOT v.substituido",
        episodeJoin("v"),
      ),
    ],
  },
  documentos: {
    permissions: ["documentos:ler"],
    sql: [
      project(
        "documento_versao_consulta",
        "v",
        "v.paciente_id",
        "s.episodio_id",
        "v.autor_id",
        "documento",
        "registro",
        "CASE WHEN v.aprovado THEN 'aprovado_dev' ELSE 'nao_aprovado' END",
        "NULL::timestamptz",
        "v.criada_em",
        "NOT v.ha_versao_posterior",
        "JOIN solicitacao_documento s ON s.organizacao_id=v.organizacao_id AND s.id=v.solicitacao_id",
      ),
    ],
  },
  agenda: {
    permissions: ["agenda:ler"],
    sql: [
      project(
        "agendamento_versao_consulta",
        "v",
        "v.paciente_id",
        "NULL::uuid",
        "v.autor_id",
        "agendamento",
        "planejamento",
        "v.situacao",
        "v.inicio",
        "v.criada_em",
        "v.atual",
      ),
    ],
  },
  preventivos_externos: {
    permissions: ["protocolos:ler"],
    sql: [
      project(
        "aplicacao_preventiva_consulta",
        "v",
        "v.paciente_id",
        "NULL::uuid",
        "v.autor_id",
        "aplicacao_externa",
        "declaracao_externa",
        "'declarada'::text",
        "v.ocorrida_em",
        "v.criada_em",
        "v.ativa",
        "WHERE v.origem='externa'",
      ),
    ],
  },
};
